### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by figure002** [mjpieters/formatflowed#1]
The library currently does not work with Python 3 because you do:

    line = line.decode(self.character_set, self.error_handling)

The `decode()` method does not exist in Python 3, where strings are Unicode by default. If you make the decode step optional, it should work in Python 3 as well.

**Comment by mjpieters** [comment]
I'll certainly take a look; I haven't touched this project in years, but I'd like to see Py3 support here.

**Comment by mjpieters** [comment]
I've released version 2.0.0 on PyPI; but note that decoding is *still required*, as the library is designed to handle format=flowed mime payloads (which are bytes).

**Comment by figure002** [comment]
Amazing! Thank you for updating this on such short notice.
